version: '3.7'
services:
  backend:
    build: 
      context: backend
      dockerfile: docker/Dockerfile
      args:
        - UID=1000
    env_file:
      - ./backend/.env.example
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: nest-overview
      POSTGRES_PASSWORD: nest-overview
      ALLOW_IP_RANGE: 0.0.0.0/0
    command: -c log_min_messages=PANIC -c log_min_error_statement=PANIC
      
