version: '3.7'
services:
  backend:
    ports:
      - 3000:3000/tcp
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: npm run start:prod

  db:
    ports:
      - "15432:5432"
